### ISSUE TITLE
[🐛BUG] general类没办法使用value-based metrics

### ISSUE THREAD

**Issue by DSTTSD** [RUCAIBox/RecBole#1008]
请问怎么样才能在general类中使用value-based metrics呢，我在yaml中设置了eval_setting: RO_RS,labeled以及数据集，但是在运行中仍然报了NotImplementedError: Full sort evaluation do not match value-based metrics!，我在打印final_config_dict后发现mode的类型仍然是预置的‘full’

**Comment by chenyuwuxin** [comment]
@DSTTSD 我在netflix数据集使用value-based metrics运行BPR模型没有遇到问题，可能是你的配置的yaml文件部分参数设置出现了问题，能否提供具体的yaml文件内容？另外，关于yaml评测参数的设置，可以参考[Evaluation Settings](https://recbole.io/docs/user_guide/config/evaluation_settings.html)。

**Comment by chenyuwuxin** [comment]
@DSTTSD 这种格式是错误的，你可以参考以下格式进行设置：
```
eval_args:
  group_by: ~
  split: {'RS':[0.8, 0.1, 0.1]}
  mode: labeled
  order: RO
valid_metric: AUC
metrics: ['AUC']
group_by_user: False
```
