### ISSUE TITLE
给Pop使用留一法出现索引错误

### ISSUE THREAD

**Issue by tctctctctc** [RUCAIBox/RecBole#1041]
**描述这个 bug**
当对Pop模型使用留一法划分数据时，提示IndexError: tensors used as indices must be long, byte or bool tensors

**如何复现**
复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件
```yaml
  # data config
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  load_col:
    inter: [user_id, item_id, timestamp]
  unused_col:
    inter: [timestamp]
  
  # model config
  embedding_size: 64
  
  # training and evaluation config
  epochs: 500
  train_batch_size: 4096
  eval_batch_size: 4096
  neg_sampling:
    uniform: 1
  eval_args:
    group_by: user
    order: RO
    split: {'LS': 'valid_and_test'}
    mode: uni100
  metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
  topk: 10
  valid_metric: MRR@10
  metric_decimal_place: 4
```
2. 您的代码
3. 您的运行脚本

```ptyhton
if __name__ == '__main__':
    run_recbole(model='Pop', dataset='ml-100k', config_file_list=['test.yaml'])
```
**预期**
对您的预期作清晰简明的描述。

**屏幕截图**
![image](https://user-images.githubusercontent.com/31268918/141424544-3bddbb5e-d220-45b6-9811-9a6728299ae3.png)

**链接**
添加能够复现 bug 的代码链接，如 Colab 或者其他在线 Jupyter 平台。（可选）

**实验环境（请补全下列信息）：**
 - 操作系统: Windows10
- RecBole 版本 1.0.0
 - Python 版本 3.6.8
- PyTorch 版本 1.10.0
- cudatoolkit 版本 none
