### ISSUE TITLE
[💡SUG] Tensorboard Logging All Metrics

### ISSUE THREAD

**Issue by RuihongQiu** [RUCAIBox/RecBole#1059]
**Is your feature request related to a problem? Please describe.**

I was using the newly added Tensorboard feature.

The current version has the `Valid_score`, which seems to only contain the `valid_metric` from the `configuration yaml` file.

Is it possible to log every chosen metrics from the `configuration yaml`?

For example, here is my `yaml`:
```yaml
metrics: ["Recall", "MRR", "NDCG", "Precision"]
topk: [5, 10, 20, 50]
valid_metric: MRR@10
```

The current Tensorboard only has 'MRR@10' in `Valid_score`. Is it possible to log every other metrics?

One last question is that the train loss after convergence looks too large in scale. Is it because it's the sum of the batch rather than the mean?
![image](https://user-images.githubusercontent.com/17882988/143815988-32d651c4-6f3c-4c6a-b105-ed4ba2ab7c2e.png)

Thank you for the great repo again!
