### ISSUE TITLE
模型评价标准rmse的困惑

### ISSUE THREAD

**Issue by cangshu420** [RUCAIBox/RecBole#1096]
你好，感谢你们团队做的这个项目，用起来十分方便，但我现在遇到了一个问题，希望得到解答。
我使用DMF模型进行数据的训练，然后在评估模型的时候，我使用的是metrics是rmse和auc，但在计算rmse的时候，感觉值很小，然后我看了一下源代码，我发现rmse的真实值是通过“data.label”获取的，预测值是“rec.score”获得的，但我debug之后发现获得的真实值只有0和1，而预测值是介于【0，1】之间，我的疑惑是这个真实值是怎么产生的，为什么只有0和1，而不是一个连续值，这里能否帮我解答一下，谢谢！ 这里其实我比较想要的是连续的真实值

以下是我的yaml文件中的评估文件的配置部分
```yaml
#evalution settings

eval_args:
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: uni10
repeatable: True
group_by_user: True #是否将一个user的记录划到一个组里，当eval_setting使用RO_RS的时候该项必须是True
split_ratio: [0.8,0.1,0.1] #切分比例
metrics: ["AUC", "RMSE", "MAE"] #评测标准
topk: [10] #评测标准使用topk，设置成10评测标准就是["Recall@10", "MRR@10", "NDCG@10", "Hit@10", "Precision@10"]
valid_metric: RMSE #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size
```
