### ISSUE TITLE
[🐛BUG] Not able to generate and save recommended items from FM (CARS). 

### ISSUE THREAD

**Issue by SlokomManel** [RUCAIBox/RecBole#1099]
**The bug**
I am running FM using additonal user features as contextual information.  

**To Reproduce**
1. yaml file
```
# Training and evaluation config
data_path: 
epochs: 50
train_batch_size: 4096
eval_batch_size: 4096
neg_sampling: ~
load_col:
    inter: [user_id, item_id, rating, timestamp]
    user: [user_id, gender] #  age, gender, occupation, zip_code]
threshold:
    rating: 3
TIME_FIELD: timestamp
eval_args:
    group_by: ~
    order: TO
    split: {'RS': [0.8,0.1,0.1]}
    mode: uni1000 # Not able to use neither labeled nor full options!

metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy']
topk: 50
valid_metric: MRR@50
metric_decimal_place: 4
eval_step: 10
save_dataset: True
save_dataloaders: True
reproducibility: True
seed: 2020
filter_inter_by_user_or_item: True
user_inter_num_interval: [20, 1500]
```
2. Code
```
from recbole.quick_start import run_recbole
from recbole.utils.case_study import full_sort_topk

config_file_list= ['test.yaml']
run_recbole(model='FM', dataset='ml-100k', config_file_list= config_file_list)
```
3. Output results

**Expected behavior**
I get the recommendation metrics as follow: 
`Evaluate   : 100%|████████████████████████████████████████████████| 166/166 [00:07<00:00, 21.65it/s]

30 Dec 16:50    INFO  best valid : {'recall@50': 0.134, 'mrr@50': 0.2801, 'ndcg@50': 0.173, 'hit@50': 0.7411, 'precision@50': 0.1366, 'itemcoverage@50': 0.1289, 'giniindex@50': 0.957, 'shannonentropy@50': 0.0209}

30 Dec 16:50    INFO  test result: {'recall@50': 0.117, 'mrr@50': 0.2771, 'ndcg@50': 0.1783, 'hit@50': 0.6867, 'precision@50': 0.1475, 'itemcoverage@50': 0.1182, 'giniindex@50': 0.9555, 'shannonentropy@50': 0.023}
`

But once I try to run case study: `topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=50, device=config['device'])` I get the following error: 
**`AttributeError: 'NegSampleEvalDataLoader' object has no attribute 'is_sequential'`**

Looking forward to hear back from you.
Thank you.

**Comment by Wicknight** [comment]
@SlokomManel Hello,thanks for your attention to RecBole!
When using case_ study for full sort evaluation, the test_data here must be of type FullSortEvalDataloader. This is described in the [official document](https://recbole.io/docs/recbole/recbole.utils.case_study.html) and annotation of case_study.py. Here you use NegSampleEvalDataloader, so an error occurs. For details, you can check the [official document](https://recbole.io/docs/recbole/recbole.utils.case_study.html).

**Comment by SlokomManel** [comment]
Thanks for your reply. 
As for "full sort evaluation" in the case study, it works if I use any other recommendation models i.e., BPR with `full` mode but I am interested in context-aware models and I don't know why neither `full` nor `labeled` worked for me. I can use `unixxxx` or `popxxxx`.

I went through the documentation but I didn't find an alternative to solve my problem: top K recommendation using FM or other CARS models + evaluate the model on ranking based metrics i.e., precision@k, recall@k and then save the recommended items !

**Comment by Wicknight** [comment]
@SlokomManel Hello! If you want to use context recommendation via full sort evaluation, you can only load user_id and item_id. Therefore, you need to change your configuration, like:
`load_col:
    inter: [user_id, item_id]
    user: [user_id, gender] #  age, gender, occupation, zip_code]
`

**Comment by Wicknight** [comment]
@SlokomManel Hello! If you want to use context recommendation via full sort evaluation, you can only load user_id and item_id. Therefore, you need to change your configuration, like:
`
load_col:
    inter: [user_id, item_id]
    user: [user_id, gender] #  age, gender, occupation, zip_code]
`

**Comment by SlokomManel** [comment]
**`    raise ValueError(f'Field [{field}] not in inter_feat.')
ValueError: Field [rating] not in inter_feat.
`**

**Comment by Wicknight** [comment]
Sorry, the configuration here should be as follows:
`
load_col:
    inter: [user_id, item_id, rating]
    user: [user_id, gender] #  age, gender, occupation, zip_code]
unused_col:
    inter: [rating]
`

**Comment by SlokomManel** [comment]
Actually I forgot to mention that I need "Timestamp" because I use Temporal ordering with ration split.
`
eval_args:
    group_by: ~
    order: **TO**
    split: {'RS': [0.8,0.1,0.1]}`

**Comment by Wicknight** [comment]
According to the configuration you provided earlier, the following solutions are provided:
```
# Training and evaluation config
data_path: 
epochs: 50
train_batch_size: 4096
eval_batch_size: 4096
neg_sampling: ~
load_col:
         inter: [user_id, item_id, rating, timestamp]
         user: [user_id, gender] #  age, gender, occupation, zip_code]
unused_col:
    inter: [timestamp]
threshold:
    rating: 3
TIME_FIELD: timestamp
eval_args:
    group_by: user
    order: TO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full

metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy']
topk: 50
valid_metric: MRR@50
metric_decimal_place: 4
eval_step: 10
save_dataset: True
save_dataloaders: True
reproducibility: True
seed: 2020
filter_inter_by_user_or_item: True
user_inter_num_interval: [20, 1500]
```
