### ISSUE TITLE
Question: Is it possible to read a pre-defined train, validate, and test sets?

### ISSUE THREAD

**Issue by SlokomManel** [RUCAIBox/RecBole#1114]

**Comment by Wicknight** [comment]
@SlokomManel Thanks for your attention for RecBole! If you mean to use pre-defined datasets, you can use 'benchmark_filename' in the data configuration file. This parameter is used to implement the function. The usage can be viewed through [the document](https://recbole.io/docs/user_guide/config/data_settings.html).

**Comment by SlokomManel** [comment]
Thanks for the reply @Wicknight . It worked well for me. 
However, I have one problem that I thought it was solved previsouly. 
I am interested in CARS models with **unixxx mode**. `unixxx` mode is also called one-plus random evaluation (if I understood it correctly). Whenever, I use `unixxx` mode, I am not able to get the topK recommended items. 

In previous solution, I was suggested to use the `full` mode but as I just mentioned earlier in my evaluation setup, I need to use one-plus random? Possible solutions / suggestions are more than welcome. 

Thank you in advance.

**Comment by Wicknight** [comment]
@SlokomManel Hello! Can you describe in detail what the problem is? I used the above configuration file to run on my pre-defined ml-100k dataset(part1, part2, part3) and it worked. So I hope you can describe your error in detail.
And as for the unixxx mode and topK recommended items in CARS models, I think you can get the model in unixxx mode, and then you can reorganize your data into full-sort dataloader and use case_ study to recommend items on the dataloader with the model got in unixxx mode. I think it will work.

**Comment by SlokomManel** [comment]
With the following YAML, I succeeded to make the code running. 
But there is one strange thing. Knowwing that I am giving my pre-defined splits using `benchmark_filename: ['part1', 'part2', 'part3']`, in the log, I see the following
```

Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp', 'zip_code']

11 Jan 09:15    INFO  [Training]: train_batch_size = [4096] negative sampling: [None]

11 Jan 09:15    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'group_by': 'user', 'order': 'TO', 'mode': 'uni1000', **'split': {'RS': [0.8, 0.1, 0.1]}}]** 
```

I did not specify any **RS**? My data is already splitted into train (part1), val (part2), and test (part3). 

```
epochs: 200
train_batch_size: 4096
eval_batch_size: 4096
neg_sampling: ~
load_col:
         inter: [user_id, item_id, rating, timestamp]
         user: [user_id, zip_code] #  age, gender, occupation, zip_code]
LABEL_FIELD: rating
unused_col:
    inter: [timestamp]
threshold:
    rating: 3
TIME_FIELD: timestamp
eval_args:
    group_by: user
    order: TO
    mode: uni1000 

benchmark_filename: ['part1', 'part2', 'part3']

metrics: ['Precision', 'Recall', 'MRR', 'NDCG', 'Hit', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy']
topk: 50
valid_metric: MRR@50
metric_decimal_place: 4
eval_step: 10
save_dataset: True
save_dataloaders: True
reproducibility: True
seed: 2020
filter_inter_by_user_or_item: True
user_inter_num_interval: [20, 1500]
```

As for the second part, "I think you can get the model in unixxx mode, and then **you can reorganize your data into full-sort dataloader** and use case_ study to recommend items on the dataloader with the model got in unixxx mode. I think it will work." --> Sorry I am not sure that I understood your point here: How can I reorganize data into full-sort dataloader?

P.S. I am using the code in case_ study.

**Comment by Wicknight** [comment]
The **'split'** in the log file is the default value set for the model. When setting **'benchmark'** parameter,  the parameter of **'split'** is invalid, so please don't worry.
As for the second part, here is a small example.

```
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.quick_start import load_data_and_model
from recbole.config import Config
from recbole.data import create_dataset, data_preparation

if __name__ == '__main__':

    config, model, _, _, _, _ = load_data_and_model(
        model_file='xxxmodel.pth', dataset_file='xxxdataset.pth', dataloader_file='xxxdataloader.pth'
    )

    data_config = Config(model='FM', dataset='ml-100k', config_file_list=['bench.yaml'])
    dataset = create_dataset(data_config)
    train_data, valid_data, test_data = data_preparation(data_config, dataset)

    # uid_series = np.array([1, 2])  # internal user id series
    # or you can use dataset.token2id to transfer external user token to internal user id
    uid_series = dataset.token2id(dataset.uid_field, ['196', '186'])

    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])
    print(topk_score)  # scores of top 10 items
    print(topk_iid_list)  # internal id of top 10 items
    external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
    print(external_item_list)  # external tokens of top 10 items
    print()
```
I think you can get model under your following config and use **'load_data_and_model'** to load the model.
And then you can change the **'mode'**(full) in eval_args of your config (here I call it 'bench.yaml'), and use **'create_dataset'** and **'data_preparation'** to load the data.
And then you can use full_sort_topk to recommend.

**Comment by SlokomManel** [comment]
Following your instructions I got this error

`TypeError: full_like(): argument 'input' (position 1) must be Tensor, not NoneType`

**Comment by Wicknight** [comment]
There is no error when I use ml-100k data set for experiment (with 8：1：1, group by user, order by TO). I think one possible reason is that some users only appear in your test data and 'history_item' of users is None. Maybe you should check the data first.

**Comment by SlokomManel** [comment]
**_To reproduce my error:_** 

**1. Run FM model**

data [part1, part2, part3] are avaialble here: [data](https://surfdrive.surf.nl/files/index.php/s/uqIoCbqQx0Ugzd6)

YAML file to run CARS: 

```
# Training and evaluation config
epochs: 20
train_batch_size: 4096
eval_batch_size: 4096
neg_sampling: ~
load_col:
         inter: [user_id, item_id, label, timestamp]
#         user: [user_id, gender] #  age, gender, occupation, zip_code]
LABEL_FIELD: label
unused_col:
    inter: [timestamp]
TIME_FIELD: timestamp
eval_args:
    group_by: user
    mode: uni1000 # full uni1000

benchmark_filename: ['part1', 'part2', 'part3']

metrics: ['Precision', 'Recall', 'MRR', 'NDCG', 'Hit', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy']
topk: 50
valid_metric: MRR@50
metric_decimal_place: 4
eval_step: 10
save_dataset: True
save_dataloaders: True
reproducibility: True
seed: 2020

```
Then, run.py: 

```
from recbole.quick_start import run_recbole

config_file_list= ['test.yaml']
run_recbole(model='FM', dataset='ml100k', config_file_list= config_file_list)

```
This works fine for me. I get the following scores: 

`12 Jan 12:15    INFO  test result: {'precision@50': 0.0076, 'recall@50': 0.0764, 'mrr@50': 0.0273, 'ndcg@50': 0.0326, 'hit@50': 0.316, 'itemcoverage@50': 0.054, 'giniindex@50': 0.9632, 'shannonentropy@50': 0.0494}`

**2. Generate TopK recommendation**

```
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.quick_start import load_data_and_model
from recbole.config import Config
from recbole.data import create_dataset, data_preparation

if __name__ == '__main__':

    config, model, _, _, _, _ = load_data_and_model(
        model_file='saved/FM-Jan-12-2022_12-03-49.pth', dataset_file='saved/ml100k-dataset.pth', dataloader_file='saved/ml100k-for-FM-dataloader.pth'
    )
    aa = list(range(1, 846))
    aa = output = [str(x) for x in aa] # map(str, aa)
    data_config = Config(model='FM', dataset='ml100k', config_file_list=['test.yaml'])
    dataset = create_dataset(data_config)
    train_data, valid_data, test_data = data_preparation(data_config, dataset)

    # uid_series = np.array([1, 2])  # internal user id series
    # or you can use dataset.token2id to transfer external user token to internal user id

    uid_series = dataset.token2id(dataset.uid_field, list (aa))
    print(uid_series)

    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])
    print(topk_score)  # scores of top 10 items
    print(topk_iid_list)  # internal id of top 10 items
    external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
    print(external_item_list)  # external tokens of top 10 items
    print()
```

But before running this I change my YAML file. Specifically, I modify FROM: 

```
eval_args:
    group_by: user
    mode: uni1000 # full uni1000
```

To:

```
eval_args:
    group_by: user
    mode: full 
```

Error: **KeyError: 'timestamp'**

I checked other Issues in GitHub and I found that we need to use` unused_col:     inter: [timestamp]` and it is actually used in my YAML.
