### ISSUE TITLE
关于GCMC训练rmse过大的问题

### ISSUE THREAD

**Issue by cangshu420** [RUCAIBox/RecBole#1117]
你好，我最近在使用GCMC模型都ml-100k数据集进行训练，但是得到的rmse能达到超过3，这个明显是不正常的，原论文中对与ml-1m进行测试得到的结果rmse也就0.8-0.9左右，我现在不确定是不是我的配置文件有问题，希望能帮我解答一下,以下是我的配置文件：

```yaml
# Atomic File Format
field_separator: "\t"
seq_separator: " "

# Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
seq_len: ~
# Sequential Model Needed
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
# Knowledge-based Model Needed
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id

# Selectively Loading
load_col:
    inter: [user_id, item_id, rating, timestamp]


# training settings
epochs: 500 #训练的最大轮数
train_batch_size: 4096 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
training_neg_sample_num: 1 #负采样数目
eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了



# evalution settings
eval_args:
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: labeled
LABEL_FIELD: rating
NEG_PREFIX: neg_
repeatable: False
group_by_user: True #是否将一个user的记录划到一个组里，当eval_setting使用RO_RS的时候该项必须是True
split_ratio: [0.8,0.1,0.1] #切分比例
metrics: [ "RMSE", "MAE"] #评测标准
valid_metric: RMSE #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size

# general
gpu_id: 0
use_gpu: True
#seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False


accum: "stack"
gcn_output_dim: 500
embedding_size: 64
dropout_prob: 0.3
sparse_feature: True
class_num: 2
num_basis_functions: 2
```

如果不是配置文件的原因，希望帮我解答一下造成这种结果的原因是什么，万分感谢
[Jan-12-2022_10-43-30.log](https://github.com/RUCAIBox/RecBole/files/7851286/Jan-12-2022_10-43-30.log)
