### ISSUE TITLE
[🐛BUG] 在Context-aware的模型的配置参数中，是否TIME_FIELD一定要用？

### ISSUE THREAD

**Issue by sxhysj** [RUCAIBox/RecBole#1139]
**描述这个 bug**
我使用NFM、LightGBM模型的时候，会遇到如下错误：

```
  File "/home/abc/anaconda3/envs/kaggle/lib/python3.9/site-packages/recbole/data/interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 't_dat'
```

相应的参数表设置为：
```
field_separator: ","
seq_separator: " "

# Common Features
USER_ID_FIELD: customer_id
ITEM_ID_FIELD: article_id
RATING_FIELD: price
TIME_FIELD: t_dat
seq_len: ~

# Selectively Loading
load_col:
    inter: [t_dat, customer_id, article_id, price, sales_channel_id]
    item: [article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,col\
our_group_code,colour_group_name,perceived_colour_value_id,perceived_colour_value_name,perceived_colour_master_id,perceived_colour_master_name,departme\
nt_no,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc]
    user: [customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code]
unload_col: ~
unused_col: ~

eval_args:
    group_by: user
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'MAP']
topk: 10
valid_metric: MRR@10
metric_decimal_place: 4

threshold:
    price: 0.01
```

**timestamp列的数据形式为：**
```
2018-09-20
2018-09-20
2018-09-20
2018-09-21
```

**实验环境：**
 - 操作系统: [如 Linux, macOS 或 Windows]
- RecBole 版本 [1.0.0]
 - Python 版本 [如 3.9.7]
- PyTorch 版本 [如 1.10.2]
- cudatoolkit 版本 [11.3.1]

我的问题是：这个的timestamp是日期，似乎是这个问题导致了keyerror的错误。我是否可以在context-aware模型中不适用time_field字段呢？time_field字段可以用日期吗？
