### ISSUE TITLE
[🐛BUG] full_sort_scores does not work with context-aware models

### ISSUE THREAD

**Issue by PontusAlma** [RUCAIBox/RecBole#1140]
I'm trying to predict item scores for users with full_sort_scores after training a model. However, full_sort_scores does not seem to work with context-aware models such as DeepFM (also tried with a few others such as xDeepFM). Here's a toy example to reproduce the error:
```
from logging import getLogger
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.data.interaction import Interaction
from recbole.model.context_aware_recommender import DeepFM
from recbole.trainer import Trainer
from recbole.utils import init_seed, init_logger
from recbole.utils.case_study import full_sort_scores, full_sort_topk

if __name__ == '__main__':
    # configurations initialization
    config = Config(model='DeepFM', dataset='ml-100k')

    # init random seed
    init_seed(config['seed'], config['reproducibility'])

    # logger initialization
    init_logger(config)
    logger = getLogger()

    # write config info into log
    logger.info(config)

    # dataset creating and filtering
    dataset = create_dataset(config)
    logger.info(dataset)

    # dataset splitting
    train_data, valid_data, test_data = data_preparation(config, dataset)

    # model loading and initialization
    model = DeepFM(config, train_data.dataset).to(config['device'])
    logger.info(model)

    # trainer loading and initialization
    trainer = Trainer(config, model)

    # model training
    best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)

    # model evaluation
    test_result = trainer.evaluate(test_data)
    print(test_result)

    # case study
    uid_series = dataset.token2id(dataset.uid_field, ['196', '186'])
    score = full_sort_scores(uid_series, model, test_data, device=config['device'])
    print(score)  # score of all items
    print(score[0, dataset.token2id(dataset.iid_field, ['242', '302'])])
```
Output:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_3080\1844443578.py in <module>
     46     # case study
     47     uid_series = dataset.token2id(dataset.uid_field, ['196', '186'])
---> 48     score = full_sort_scores(uid_series, model, test_data, device=config['device'])
     49     print(score)  # score of all items
     50     print(score[0, dataset.token2id(dataset.iid_field, ['242', '302'])])

~\Miniconda3\envs\recbole-test\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

~\Miniconda3\envs\recbole-test\lib\site-packages\recbole\utils\case_study.py in full_sort_scores(uid_series, model, test_data, device)
     40     model.eval()
     41 
---> 42     if not test_data.is_sequential:
     43         index = np.isin(test_data.user_df[uid_field].numpy(), uid_series)
     44         input_interaction = test_data.user_df[index]

AttributeError: 'NegSampleEvalDataLoader' object has no attribute 'is_sequential'
```

However, if I replaced DeepFM with BPR (or any other algorithm) from the general recommendation algorithms, everything works fine:
```
from logging import getLogger
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.data.interaction import Interaction
from recbole.model.general_recommender import BPR
from recbole.trainer import Trainer
from recbole.utils import init_seed, init_logger
from recbole.utils.case_study import full_sort_scores, full_sort_topk

if __name__ == '__main__':
    # configurations initialization
    config = Config(model='BPR', dataset='ml-100k')

    # init random seed
    init_seed(config['seed'], config['reproducibility'])

    # logger initialization
    init_logger(config)
    logger = getLogger()

    # write config info into log
    logger.info(config)

    # dataset creating and filtering
    dataset = create_dataset(config)
    logger.info(dataset)

    # dataset splitting
    train_data, valid_data, test_data = data_preparation(config, dataset)

    # model loading and initialization
    model = BPR(config, train_data.dataset).to(config['device'])
    logger.info(model)

    # trainer loading and initialization
    trainer = Trainer(config, model)

    # model training
    best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)

    # model evaluation
    test_result = trainer.evaluate(test_data)
    print(test_result)

    # case study
    uid_series = dataset.token2id(dataset.uid_field, ['196', '186'])
    score = full_sort_scores(uid_series, model, test_data, device=config['device'])
    print(score)  # score of all items
    print(score[0, dataset.token2id(dataset.iid_field, ['242', '302'])])
```

Output: 
```
{'recall@10': 0.2523, 'mrr@10': 0.4855, 'ndcg@10': 0.292, 'hit@10': 0.7953, 'precision@10': 0.1962}
tensor([[   -inf,  1.7270,  1.8214,  ..., -4.2845, -4.4077, -3.4571],
        [   -inf,  1.3916,    -inf,  ..., -4.2441, -4.1464, -3.8011]])
tensor([1.7270, 1.8214])
```

I'm actually working with my own dataset where I first discovered this error. Initially I thought that I might be missing something, but as I was able to reproduce the error with this toy example, I guess it's a RecBole bug?

**Desktop:**
- OS: Windows
- RecBole Version: 1.0.0
- Python Version: 3.7.11
- PyTorch Version: 1.10.2+cpu
- cudatoolkit Version: -

**Comment by chenyuwuxin** [comment]
@PontusAlma Hello , thanks for your attention to RecBole!
We can only support contextual information containing users or items(in **.user** or **.item** file) if you want to use `full_sort_scores` , and other context information is not supported(e.g. time). In particular, context-aware does not support negative sampling , because we can't construct the context information of negative examples(e.g. click time). Therefore, please do not use negative sampling and don't try to use other information of **.inter** file except users and items.

**Comment by chenyuwuxin** [comment]
@PontusAlma Different types of models play different roles in the recommendation process. General models are generally used for recall tasks which only use user_id and item_id in **.inter** file. However, the context-aware models are often used for sorting tasks which need not only user_id and item_id, but also other context information. If you want to use context-aware models for recall task , you can only include user side or item side features to train the model.

**Comment by PontusAlma** [comment]
@chenyuwuxin Thank you again for your answer. 
My goal is to train a DeepFM model, and use that model to get top K recommended items for user X. In other words, after training a model, I want to see which items the model actually recommends and the item scores for a particular user. This is because I want to qualitatively assess how good the model is at recommendation, aside from the training/test statistics. And I want to include user and/or item metadata in the model to get (presumably) better recommendations. Is this possible and how?

Also having re-read your first answer a few times, maybe I misunderstood you initially. So do you mean that I can include user/item metadata in the **.user** (e.g., gender, age) and/or **.item** (e.g., genres) files, and as long as I dropped any contextual information from the **.inter** file (e.g., timestamp) and set neg_sampling to None, then full_sort_scores would work with DeepFM?

**Comment by chenyuwuxin** [comment]
@PontusAlma Yes, your understanding is completely correct. You just need to divide all context information into user side and item side, and put them in **.user** and **.item** file. And set neg_sampling to **None**, training the model according to this configuration.

**Comment by PontusAlma** [comment]
@chenyuwuxin I tried that but I'm getting a `ValueError: neg_sampling:[None] should be a dict.` after setting setting `neg_sampling: None` in the config.yaml file.

**Comment by chenyuwuxin** [comment]
@PontusAlma Set `neg_sampling: ~`.

**Comment by PontusAlma** [comment]
@chenyuwuxin I tried with those settings, but got the following error when using full_sort_scores:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11148\1425637129.py in <module>
      1 #uid_series = dataset.token2id(dataset.uid_field, [str(uid) for uid in ratings['userId:token'].sample(5).values])
      2 uid_series = dataset.token2id(dataset.uid_field, ['196', '186'])
----> 3 topk_score, topk_iid_list = full_sort_scores(uid_series, model, test_data, device=config['device'])
      4 print(topk_score)  # scores of top 10 items
      5 print(topk_iid_list)  # internal id of top 10 items

~\Miniconda3\envs\recbole-with-torch-cuda-env\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

~\Miniconda3\envs\recbole-with-torch-cuda-env\lib\site-packages\recbole\utils\case_study.py in full_sort_scores(uid_series, model, test_data, device)
     44         input_interaction = test_data.user_df[index]
     45         history_item = test_data.uid2history_item[uid_series]
---> 46         history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)])
     47         history_col = torch.cat(list(history_item))
     48         history_index = history_row, history_col

~\Miniconda3\envs\recbole-with-torch-cuda-env\lib\site-packages\recbole\utils\case_study.py in <listcomp>(.0)
     44         input_interaction = test_data.user_df[index]
     45         history_item = test_data.uid2history_item[uid_series]
---> 46         history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)])
     47         history_col = torch.cat(list(history_item))
     48         history_index = history_row, history_col

TypeError: full_like(): argument 'input' (position 1) must be Tensor, not NoneType
```

I'm actually loading a trained model after some hyperparameter optimization, not sure whether that's the problem here.

**Comment by thigazholi-official** [comment]
How do we run the same on labeled dataset?
I am facing similar issues with full_sort_scores for EulerNet model. After training with mode: labeled, trying out full_sort_scores throws uid2history_item error

**Comment by yzy945** [comment]
> How do we run the same on labeled dataset? I am facing similar issues with full_sort_scores for EulerNet model. After training with mode: labeled, trying out full_sort_scores throws uid2history_item error

me too

**Comment by adhiiisetiawan** [comment]
same with me 

i use this following script to predict

```python3
import torch
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.quick_start import load_data_and_model

config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
    model_file="saved/DCNV2-May-21-2024_08-19-16.pth",
)

# uid_series = np.array([1, 2])  # internal user id series
# or you can use dataset.token2id to transfer external user token to internal user id
uid_series = dataset.token2id(dataset.uid_field, ["1"])
uid_series

# THE ERROR IS HERE, in full_sort_scores
topk_score, topk_iid_list = full_sort_topk(
    uid_series, model, test_data, k=10, device=config["device"]
)

print(topk_score)  # scores of top 10 items
# print(topk_iid_list)  # internal id of top 10 items
external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
print(external_item_list)  # external tokens of top 10 items
print()



score = full_sort_scores(uid_series, model, test_data, device=config["device"])
print(score)  # score of all items
print(score[0, dataset.token2id(dataset.iid_field, ["10137"])])  # score of item ['242', '302'] for user '196'.
```


here's the error

```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], [line 1](vscode-notebook-cell:?execution_count=4&line=1)

AttributeError: 'NegSampleEvalDataLoader' object has no attribute 'uid2history_item'
```

and here's my config

```yaml
# Environment Settings
gpu_id: '0'
worker: 16
seed: 2020
checkpoint_dir: 'saved/'
log_wandb: False
wandb_project: 'context-aware-RS'

# dataset config : General Recommendation
# USER_ID_FIELD: user_id
# ITEM_ID_FIELD: item_id
# load_col:
#     inter: [user_id, item_id]

# model config
mixed: False                # (bool) The structure of cross network.
structure: 'parallel'        # (string) The combination method between cross network and deep network.
cross_layer_num: 4          # (int) The number of cross network layers.
expert_num: 4               # (int) The number of experts in mixed cross network.
low_rank: 256               # (int) The size of low rank space.
embedding_size: 16          # (int) The embedding size of features.
mlp_hidden_size: [562, 768, 1024] # (list of int) The hidden size of deep network.
reg_weight: 2               # (int) The L2 regularization weight.
dropout_prob: 0.2           # (float) The dropout rate.

# Training and evaluation config
epochs: 1
learner: adam
learning_rate: 0.0001
train_batch_size: 128
eval_batch_size: 128
stopping_step: 10
threshold: {'rating': 4}
load_col: 
    inter: ['user_id', 'item_id', 'rating']
    user: ['user_id', 'age', 'gender', 'occupation']
    item: ['item_id', 'release_year', 'class']
eval_args:
  split: {'RS':[0.8,0.1,0.1]}
  order: RO
  group_by: ~
  mode: labeled
metrics: ['AUC', 'LogLoss']
valid_metric: AUC
neg_sampling: ~

```

cc: @Ethan-TZ
