### ISSUE TITLE
请问一下如何使用模型对用户进行预测？

### ISSUE THREAD

**Issue by Mintanxon** [RUCAIBox/RecBole#1181]
用自定义的数据和配置文件训练好了模型，使用文档提供的API进行预测：
```python
config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
    model_file='saved/BPR-Mar-09-2022_13-43-24.pth',
)

#定义测试的uid和topk
test_user_ids = ['21556', '46401', '53116', '82566']
k = 5

#使用recbole.utils.case_study.full_sort_topk
uid_series = dataset.token2id(dataset.uid_field, test_user_ids)
topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k, device=config['device'])
external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())

print(topk_score)
print(topk_iid_list)
print(external_item_list)

#使用model.full_sort_predict
scores = model.full_sort_predict({'user_id': torch.tensor(uid_series)}).view(len(test_user_ids), -1)
topk_score, topk_iid_list = scores.topk(k, dim=1)
external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())

print(topk_score)
print(topk_iid_list)
print(external_item_list)
```
这两个方法的结果有很大差别：
```shell
#使用recbole.utils.case_study.full_sort_topk
tensor([[-0.1962, -0.4722, -0.8933, -0.8948, -0.9057],
        [-0.2325, -0.6116, -0.8257, -0.8824, -0.8857],
        [-0.1832, -0.4728, -0.5081, -0.9317, -0.9372],
        [-0.3349, -0.3715, -0.8757, -0.8969, -0.9123]])
tensor([[ 2,  4,  9, 10,  6],
        [ 2,  1,  6,  9, 12],
        [ 2,  4,  1, 10, 13],
        [ 4,  2,  6, 13,  9]])
[['645' '6' '231' '58' '272']
 ['645' '644' '272' '231' '60']
 ['645' '6' '644' '58' '49']
 ['6' '645' '272' '49' '231']]

#使用model.full_sort_predict
tensor([[ 2.4711,  0.2503, -0.1962, -0.4722, -0.5366],
        [ 2.5352,  0.2044, -0.2325, -0.3879, -0.6116],
        [ 2.5432,  0.2282, -0.1832, -0.4728, -0.5081],
        [ 2.5696,  0.2166, -0.3349, -0.3715, -0.5009]], grad_fn=<TopkBackward>)
tensor([[3, 0, 2, 4, 1],
        [3, 0, 2, 4, 1],
        [3, 0, 2, 4, 1],
        [3, 0, 4, 2, 1]])
[['1' '[PAD]' '645' '6' '644']
 ['1' '[PAD]' '645' '6' '644']
 ['1' '[PAD]' '645' '6' '644']
 ['1' '[PAD]' '6' '645' '644']]
```
想请问下这两个方法的区别是什么？第一种对测试集的预测并不是使用模型的predict方法吗？在第二个方法中出现的商品ID为[PAD]对应的是什么意思？

还有另外一个问题，在数据集中会有很大部分是未登录用户（即没有user_id）与商品进行交互的记录，这些记录应该如何进行训练？模型预测的时候如何对未登录用户进行预测呢？

**Comment by Mintanxon** [comment]
@Sherry-XLL 感谢回复！我在调用案例分析的接口时，有的user_id会报这样的错：
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_424587/465041136.py in <module>
     11     return external_item_list  # external tokens of top k items
     12 
---> 13 top_ranked_book_ids = get_top_k_ranked_items(test_user_ids, k)

/tmp/ipykernel_424587/465041136.py in get_top_k_ranked_items(test_user_ids, k)
      3 def get_top_k_ranked_items(test_user_ids, k):
      4     uid_series = dataset.token2id(dataset.uid_field, test_user_ids)
----> 5     topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k, device=config['device'])
      6     external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
      7 

~/RecBole/recbole/utils/case_study.py in full_sort_topk(uid_series, model, test_data, k, device)
     89             - topk_index (torch.Tensor): The index of topk items, which is also the internal ids of items.
     90     """
---> 91     scores = full_sort_scores(uid_series, model, test_data, device)
     92     return torch.topk(scores, k)

~/miniconda3/envs/recbole/lib/python3.9/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     24         def decorate_context(*args, **kwargs):
     25             with self.__class__():
---> 26                 return func(*args, **kwargs)
     27         return cast(F, decorate_context)
     28 

~/RecBole/recbole/utils/case_study.py in full_sort_scores(uid_series, model, test_data, device)
     45         input_interaction = dataset.join(Interaction({uid_field: uid_series}))
     46         history_item = test_data.uid2history_item[list(uid_series)]
---> 47         history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)])
     48         history_col = torch.cat(list(history_item))
     49         history_index = history_row, history_col

~/RecBole/recbole/utils/case_study.py in <listcomp>(.0)
     45         input_interaction = dataset.join(Interaction({uid_field: uid_series}))
     46         history_item = test_data.uid2history_item[list(uid_series)]
---> 47         history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)])
     48         history_col = torch.cat(list(history_item))
     49         history_index = history_row, history_col

TypeError: full_like(): argument 'input' (position 1) must be Tensor, not NoneType
```
我将第46行的结果输出：
```python
> print(test_data.uid2history_item[list(uid_series)])
[tensor([1, 3]) None tensor([3, 4]) tensor([3]) None None tensor([1, 3])]
```
这个报错是不是因为测试集中不存在用户交互过的商品？（该用户在数据集中出现过，但是交互次数较少）
请问这个问题可以解决吗？

**Comment by Sherry-XLL** [comment]
@Mintanxon 若测试集中不存在用户交互过的商品，则无法对其进行评测，可以选择在训练的时候通过设置 `user_inter_num_interval` 过滤掉交互较少地用户。

**Comment by sxhysj** [comment]
是否可以专门针对不存在交互行为（interaction）的用户专门提供一些基础的算法，例如mean，lookalike之类的？

**Comment by sxhysj** [comment]
> @Mintanxon 若测试集中不存在用户交互过的商品，则无法对其进行评测，可以选择在训练的时候通过设置 `user_inter_num_interval` 过滤掉交互较少的用户。

试过了，还是一样的结果。我贴出我的配置文件：
```
# Atomic File Format
field_separator: ","
seq_separator: " "

# Common Features
USER_ID_FIELD: customer_id
ITEM_ID_FIELD: article_id

# Selectively Loading
load_col:
    #inter: [user_id, item_id, rating, timestamp]
    inter: [t_dat, customer_id, article_id, price, sales_channel_id]
    item: [article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,perceived_colour_value_id,perceived_colour_value_name,perceived_colour_master_id,perceived_colour_master_name,department_no,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc]
    user: [customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code]
unload_col: ~
unused_col: ~

eval_args:
    group_by: user
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'MAP']
topk: 12
valid_metric: MRR@12
metric_decimal_place: 4

#traning parameters
train_batch_size: 2048
eval_batch_size: 2048

#filter out no interaction users
user_inter_num_interval: "[1,inf)"
```
