### ISSUE TITLE
valid_metric_bigger: False 设置失败

### ISSUE THREAD

**Issue by nielei0128** [RUCAIBox/RecBole#1195]
我在`WideDeep.yaml` 中设定` valid_metric: LogLoss`以及`valid_metric_bigger: False`,但是当我运行`config=Config(model='WideDeep',dataset='criteo_sample',config_file_list=['WideDeep.yaml'])`,后config[valid_metric_bigger"]仍为True。
请问应当如何解决这个问题？谢谢！
这是我的配置文件内容：
```
data_path: .\dataset

# dataset config
dataset: 'criteo_sample'
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: ~
ITEM_ID_FIELD: ~
LABEL_FIELD: label
TIME_FIELD: index

load_col: 
    inter: '*'

fill_nan: True
normalize_all: True


# training and evaluation
show_progress: False
dropout_prob: 0.4
epochs: 500
train_batch_size: 4096
eval_args:
  mode: labeled
  group_by: ~
metrics: ['AUC', 'LogLoss']
valid_metric: LogLoss
valid_metric_bigger: False



# model
model: 'WideDeep'
embedding_size: 100
```
以下是config运行后的结果：
```
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = .\dataset\criteo_sample
show_progress = False

Training Hyper Parameters:
checkpoint_dir = saved
epochs = 500
train_batch_size = 4096
learner = adam
learning_rate = 0.001
training_neg_sample_num = 0
training_neg_sample_distribution = uniform
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
draw_loss_pic = False
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_setting = RO_RS
group_by_user = False
split_ratio = [0.8, 0.1, 0.1]
leave_one_num = 2
real_time_process = False
metrics = ['AUC', 'LogLoss']
topk = [10]
valid_metric = Logloss
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator = 	
seq_separator =  
USER_ID_FIELD = None
ITEM_ID_FIELD = None
RATING_FIELD = rating
TIME_FIELD = index
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': '*'}
unload_col = None
unused_col = None
additional_feat_suffix = None
lowest_val = None
highest_val = None
equal_val = None
not_equal_val = None
max_user_inter_num = None
min_user_inter_num = 0
max_item_inter_num = None
min_item_inter_num = 0
fields_in_same_space = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id

Other Hyper Parameters: 
embedding_size = 100
mlp_hidden_size = [32, 16, 8]
dropout_prob = 0.4
rm_dup_inter = None
filter_inter_by_user_or_item = True
SOURCE_ID_FIELD = source_id
TARGET_ID_FIELD = target_id
benchmark_filename = None
MODEL_TYPE = ModelType.CONTEXT
fill_nan = True
eval_args = {'mode': 'labeled', 'group_by': None}
valid_metric_bigger = True
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.INDIVIDUAL
device = cpu
train_neg_sample_args = {'strategy': 'none'}
```
