### ISSUE TITLE
[🐛BUG] hyperopt version 0.2.5 still doesn't work

### ISSUE THREAD

**Issue by jiho-kang** [RUCAIBox/RecBole#1354]
## 0. Parameters I used
```
fixed_str = '''
    data_path: /content/drive/MyDrive/추천솔루션고도화/Recbole/bibly/dataset/
    dataset: bibly
    field_separator: "\t"
    USER_ID_FIELD: user_id
    ITEM_ID_FIELD: item_id
    RATING_FIELD: ~
    TIME_FIELD: timestamp
    show_progress: True
    
    load_col:
        inter: [user_id, item_id, timestamp]
        user: [user_id]
        item: [item_id]
    
    model: DeepFM
    epochs: 50
    user_inter_num_interval: "[5, inf)"
    item_inter_num_interval: "[5, inf)"
    filter_inter_by_user_or_item: false
    neg_sampling:
        uniform: 1
        
    eval_args:
        split: {'RS': [4, 1, 1]}
        group_by: None
        order: TO
        mode: uni50
    metrics: ['Precision', 'Recall', 'Hit', 'MRR', 'MAP', 'NDCG', 'ItemCoverage']
    topk: [3,5,10,20]
    valid_metric: MAP@20
    
    valid_score_bigger: True
    '''

prm_str = '''
    learning_rate loguniform -7,-2
    dropout_prob loguniform -3,-1
    '''
```

## 1. hyperopt error
I've got an error like below

![image](https://user-images.githubusercontent.com/43432539/179478007-8c302a05-1ba4-46d5-b759-021ac2758cfa.png)

So I lowered the version of hyperopt to 0.2.5. But still doesn't work. same error appears like above.
![image](https://user-images.githubusercontent.com/43432539/179478375-96be82ba-8470-41a3-bce0-a4d028d784f7.png)

I'm working on Colab with `pip install recbole`

## 2. HyperTuning seems to have issue with finding best parameter

With the code below, it seems like printing the same valid result with different paramters which doesn't make sense. 
![image](https://user-images.githubusercontent.com/43432539/179480363-42d08f88-a065-43e2-87e7-b71e398666b0.png)
