### ISSUE TITLE
Understanding repeatable recommendation

### ISSUE THREAD

**Issue by tsafavi** [RUCAIBox/RecBole#1449]
Hi, I'm wondering about how repeatable recommendation is implemented. Let's assume the user history sequence is [1, 2, 3, 4, 5]. I have the following configuration: 
 ```
repeatable: True
eval_args:
    group_by: user
    order: TO
    split: {'LS': "valid_and_test"}
    mode: full
```
In this setup, item 5 is the test target label. At test time, are items [1, 2, 3, 4] filtered out from ranking? In other words, if the model outputs ranking [1, 2, 3, 4, 5] at test time, does it get a hit@1 (if 1,2,3,4 are filtered out) or no? And would the results change if `repeatable: False`?
