### ISSUE TITLE
[🐛BUG] `seq_len (dict)` 参数对超长序列特征没有起到截断 (cut off) 作用，且 `field2seqlen` 与真实长度不一致

### ISSUE THREAD

**Issue by Furyton** [RUCAIBox/RecBole#1478]
**描述这个 bug**
[文档](https://recbole.io/docs/user_guide/config/data_settings.html#basic-information)中称 `seq_len (dict)` 为 sequential feature 的最大长度，超过长度的会被截断
> `seq_len (dict)`: Keys are field names of sequence features, values are maximum length of each sequence (which means too long sequences will be cut off). If not set, the sequences will not be cut off. Defaults to `None`.

但[代码](https://github.com/RUCAIBox/RecBole/blob/9518991afef9c44f7c7e8fcce2ec62a04d555625/recbole/data/dataset/dataset.py#L512)中似乎并没有实现这一细节 (i.e., 没有进行截断)，`self.field2seqlen[field]` 直接被赋值为最大长度。

```python
self.field2seqlen[field] = max(map(len, df[field].values))
```

且 [`_dataframe_to_interaction`](https://github.com/RUCAIBox/RecBole/blob/9518991afef9c44f7c7e8fcce2ec62a04d555625/recbole/data/dataset/dataset.py#L2133) 中也会改变其长度 (可能会导致在过滤之后与 `self.field2seqlen[field]` 不一致？)

```python
new_data[k] = rnn_utils.pad_sequence(seq_data, batch_first=True)
```

**如何复现**
复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件

```yaml
# dataset config
data_path: './dataset'
dataset: 'sports'
seq_separator: "+"

USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
RATING_FIELD: 'rating'
TIME_FIELD: 'timestamp'

load_col:
    inter: ['user_id', 'item_id', 'rating', 'timestamp']
    item: ['item_id', 'categories']

seq_len: {'categories': 4} # <-- here, set max len of categories as 4
threshold: {'rating': 3}
user_inter_num_interval: '[10,inf)'
item_inter_num_interval: '[10,inf)'

save_dataset: True
save_dataloader: True

# model config
embedding_size: 10

# training and evaluation config
epochs: 10
train_batch_size: 1024
eval_batch_size: 1024
eval_args:
    split: {'RS': [0.8, 0.1, 0.1]}
    order: RO
    group_by: ~
    mode: labeled
neg_sampling: ~
metrics: ['AUC']
valid_metric: 'AUC'

repeatable: False
use_gpu: False
```

3. 您的代码
我对 Amazon Sports and Outdoors 数据集 ([由贵项目组提供的处理后的数据](https://recbole.s3-accelerate.amazonaws.com/ProcessedDatasets/Amazon_ratings/Amazon2018/Amazon_Sports_and_Outdoors.zip)) 进行了二次处理

    - item 文件仅保留 `categories` 和 `item_id`
    - 去除 `categories` 长度为 0 的 item
    - 用 `+` 将 category seq 连接 (`+` 作为 sep)
    - 示例

```csv
item_id:token	categories:token_seq
0000032042	'Other Sports'+'Dance'+'Clothing'
0000032069	'Other Sports'+'Dance'+'Clothing'
0000031860	'Other Sports'+'Dance'+'Clothing'+'Girls'+'Skirts'
0000031852	'Other Sports'+'Dance'+'Clothing'+'Girls'+'Skirts'
0000031895	'Other Sports'+'Dance'+'Clothing'+'Girls'+'Skirts'
```

5. 您的运行脚本

```python
from recbole.quick_start import run_recbole

run_recbole(model='LR', config_file_list=['cap.yaml'])
```

在 LR 模型 `__init__` 中做的小修改 (记录 `seqlen`)

```python
def __init__(self, config, dataset):
    super(LR, self).__init__(config, dataset)

    self.sigmoid = nn.Sigmoid()
    self.loss = nn.BCEWithLogitsLoss()
    # dataset: Dataset
    self.seq_len = dataset.field2seqlen # <-- here

    # parameters initialization
    self.apply(self._init_weights)
```

**预期**

模型中的输入 `interaction['categories]` 的 `size` 应当是 `[batch_size, 4]`

**屏幕截图**

![image](https://user-images.githubusercontent.com/26501227/194248485-a4106b84-e391-4420-8d6c-1b5c8a723609.png)

过滤之前 (raw) 应当是 14 (最大长度)，过滤之后变成了 10

**实验环境（请补全下列信息）：**
 - 操作系统: Windows
- RecBole 版本  1.1.0
 - Python 版本 3.9.13
- PyTorch 版本 1.12.1
