### ISSUE TITLE
Question: KeyError: 'neg_item_id'

### ISSUE THREAD

**Issue by SlokomManel** [RUCAIBox/RecBole#1535]
Model: _GCMC_
Trying to run GCMC model on movielens 100 data. I got an error about 'neg_item_id' (neg_item).
Could you please help me to find out hot to create neg_item and how can I add it to my config file? 
Thank you,

**Comment by AoiDragon** [comment]
@SlokomManel Hello,

Could you please provide more details about your question？Such as error information in console and your config file.

**Comment by SlokomManel** [comment]
@AoiDragon Thank you for your reply.
Here is my .YML file:

```
# Training and evaluation config
data_path: dataset/ml-100k
epochs: 10
learning_rate: 0.0001 
embedding_size: 64
dropout_prob: 0.4
mlp_hidden_size: [64,64,64]
neg_sampling: ~
load_col:
         inter: [user_id, item_id, label] # label represents the fact that there is an interaction between user and item
         user: [user_id, age, gender, occupation] 
LABEL_FIELD: label # cnt #label
NEG_PREFIX: neg_
eval_args:
    group_by: user
    mode: full # uni1000 # full uni1000

benchmark_filename: ['part1', 'part2', 'part3']

metrics: ['MAP', 'Precision', 'Recall', 'MRR', 'NDCG', 'Hit', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy']
topk: [5, 10, 50]
valid_metric: MAP@5 # MRR@50
metric_decimal_place: 4
save_dataset: True
save_dataloaders: True
reproducibility: True
```

The code works fine on FM but not for `BPR` and `GCMC` . I get the following error:
```
[....]
The number of users: 846
Average actions of users: 95.8130177514793
The number of items: 1575
Average actions of items: 51.43710292249047
The number of inters: 80962
The sparsity of the dataset: 93.9238245337536%
Remain Fields: ['user_id', 'item_id', 'label', 'age', 'gender', 'occupation']
16 Nov 11:29    INFO  [Training]: train_batch_size = [2048] negative sampling: [None]
16 Nov 11:29    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'group_by': 'user', 'mode': 'pop100', 'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO'}]
16 Nov 11:29    INFO  Saved split dataloaders: RecBole/dataset/ml100k-for-GCMC-dataloader.pth
RecBole/recbole/model/general_recommender/gcmc.py:168: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  i = torch.LongTensor([row, col])
16 Nov 11:29    INFO  GCMC(
  (GcEncoder): GcEncoder(
    (dropout): Dropout(p=0.4, inplace=False)
    (sparse_dropout): SparseDropout()
[...]
  File "RecBole/recbole/data/interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 'neg_item_id'
```

Thank you.

**Comment by SlokomManel** [comment]
Another minor question: Do we really need to specify a column: rating, label? How does it work when we only have `userid`, `itemid` only.

**Comment by AoiDragon** [comment]
1. I ran GCMC on ml-100k with your config file but delete `benchmark_filename`, and I didn't get any error. So I guess the problem lies in your benchmark files.
2. You can only load part of the column by specifying their name in `load_col`.
3. ItemKNN gives recommendations based on neighbor information, so it performs better with larger dataset. Also, I ran ItemKNN on ml-100k but got a much higher results than you. It may also caused by your settings of benchmark files.

**Comment by SlokomManel** [comment]
Hi @AoiDragon , actually `benchmark_filename` contains my fixed `train`, `val`, and `test` sets. 
The sets are split by time (outside Recbole) and have to be fixed for a fair comparison between different recommendation algorithms (collaborative filtering: BPRMF, MostPop, and Context-aware recommenders: FM, Graph-based recommender: GCMC).

**Comment by SlokomManel** [comment]
I took out `benchmark_filename`. I got better results such that itemKNN outperforms MostPop.
But, using same .YML file on BPR and GCMC I get same error as above
```
    File "/RecBole/recbole/trainer/trainer.py", line 168, in _train_epoch
    losses = loss_func(interaction)
  File "/RecBole/recbole/model/general_recommender/gcmc.py", line 182, in calculate_loss
    neg_item = interaction[self.NEG_ITEM_ID]
  File "/RecBole/recbole/data/interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 'neg_item_id'
```

when running FM. I get another error:
```
  File "/RecBole/recbole/trainer/trainer.py", line 168, in _train_epoch
    losses = loss_func(interaction)
  File "/RecBole/recbole/model/context_aware_recommender/fm.py", line 53, in calculate_loss
    label = interaction[self.LABEL]
  File "/RecBole/recbole/data/interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 'label'
```

**Comment by SlokomManel** [comment]
Here is my .YML:

```
# Training and evaluation config
data_path: /RecBole/dataset/ml-100k/ 
epochs: 10

train_neg_sample_args:
          sample_num: 1
          candidate_num: 1000

#neg_sampling: ~
load_col:
         inter: [user_id, item_id, rating, timestamp] 
RATING_FIELD: rating # I tried LABEL_FIELD as well

#threshold:
#    rating: 3
neg_sampling: ~
TIME_FIELD: timestamp
NEG_PREFIX: neg_
eval_args:
    group_by: user
    order: TO # TO
    split: {'RS': [0.7,0.1,0.2]}
    mode: full # uni1000 # full uni1000
unused_col:
    inter: [timestamp]
#benchmark_filename: ['part1', 'part2', 'part3']

metrics: ['MAP', 'Precision', 'Recall', 'MRR', 'NDCG', 'Hit', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy']
topk: [5, 10, 50]
valid_metric: MAP@50 # MRR@50
metric_decimal_place: 4
#eval_step: 10
save_dataset: True
save_dataloaders: True
reproducibility: True
seed: 2020
filter_inter_by_user_or_item: True


```

my ml-100k data:  in the screenshot
<img width="473" alt="Screenshot 2022-11-18 at 11 59 07" src="https://user-images.githubusercontent.com/47974112/202690041-ca53fb3d-988e-423f-bd7e-1637c90d2e49.png">

Getting same error as above, I am not sure what I am missing :( .

Thank you so much, I really appreciate your help to fix errors related to **BPR, FM, and GCMC**.
