### ISSUE TITLE
Does general model do not use item file?

### ISSUE THREAD

**Issue by PosoSAgapo** [RUCAIBox/RecBole#1553]
I am using the general model to get the result since my inter file does not contain user ratings, so I can only use general model. However, I have specified the model to use the feature included in the item file, but as I remove a column in the YAML file to see which feature is most important, the result does not change. Does this mean the general model does not use features in item files at all?
I specify the item feature column in the following way:
```
load_col:
  inter: [user, item]
  user: [user, zip_code]
  item: [item, feat_A, feat_B, feat_C, feat_D]
```
As I remove each column in the item list, the result does not change.
