### ISSUE TITLE
关于eval时 batchsize会被重设的问题

### ISSUE THREAD

**Issue by LorenzoSun-V** [RUCAIBox/RecBole#1615]
你好！作为正在入门推荐系统的CV程序员，感谢RecBole作者们长久以来维护该项目~

我在阅读源码时，有一个代码细节不太理解：

我用movielens训练DSSM时，由于train set的分布设置为none，因此batchsize会设为我在yaml文件中`train_batch_size`的值：

![image](https://user-images.githubusercontent.com/42413198/210327794-f5858314-8914-49ff-9a34-abbd1b781696.png)

但是我在eval时，由于我的yaml文件中有如下设定：
```
eval_args:
  split: {'RS':[0.8, 0.1, 0.1]}
  group_by: ~
  mode: full
  order: RO
```

因此，eval的dataloader中的batchsize会基于下图中的代码重设，而非我在yaml文件中设定的`eval_batch_size`的值：

![image](https://user-images.githubusercontent.com/42413198/210328027-7323d83f-d4d7-48d8-978e-908697230837.png)

请问为什么在`full`模式下，batchsize需要这样设定，且为什么与item_num相关？
