### ISSUE TITLE
[🐛BUG] Number of Users and Items is not the same as SASRec paper mentioned

### ISSUE THREAD

**Issue by Taekyoon** [RUCAIBox/RecBole#1648]
**Describe the bug**
I tried to test training for `amazon-beauty` dataset for the sequence recommendation model.
The number of users and items is not the same as SASRec paper mentioned.
I checked the original [SASRec paper code setting](https://github.com/kang205/SASRec/blob/e3738967fddab206d6eeb4fda433e7a7034dd8b1/data/DataProcessing.py#L38) and followed them by editing `data.yaml`.
How could this result be different? If there something I was missing, please let me know :)

**To Reproduce**
```
data.yaml

# Atomic File Format
field_separator: "\t"
seq_separator: " "

# Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
seq_len: ~
# Label for Point-wise DataLoader
LABEL_FIELD: rating
# NegSample Prefix for Pair-wise DataLoader
NEG_PREFIX: neg_
# Sequential Model Needed
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
# Knowledge-based Model Needed
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id

# Selectively Loading
load_col:
    inter: [user_id, item_id, rating, timestamp]
    item: [item_id, sales_rank, categories, price, brand]
unload_col: ~
unused_col: ~

# Filtering
rm_dup_inter: ~
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'

# Preprocessing
alias_of_user_id: ~
alias_of_item_id: ~
alias_of_entity_id: ~
alias_of_relation_id: ~
preload_weight: ~
normalize_field: ~
normalize_all: True
```

**Expected behavior**
I expected num user and items like this
![스크린샷 2023-02-16 오전 1 25 31](https://user-images.githubusercontent.com/16576921/219089515-7687daf7-d362-4e18-a50b-4de2f3cfd46a.png)
However, the recbole shows like this result.
```
15 Feb 16:31    INFO  amazon-beauty
The number of users: 22364
Average actions of users: 8.876358270357287
The number of items: 12102
Average actions of items: 16.403768283612923
The number of inters: 198502
The sparsity of the dataset: 99.92665707018277%
```

**Desktop (please complete the following information):**
 - OS: Linux
- RecBole Version v1.1.1
 - Python Version 3.8
- PyTorch Version 1.13
- cudatoolkit Version 11.2
