### ISSUE TITLE
[🐛BUG] log file not found when running on private dataset

### ISSUE THREAD

**Issue by dabasmoti** [RUCAIBox/RecBole#1797]
log file not found when running on private dataset
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/recsys_research/log/BPR/BPR-data/recbole-Jun-22-2023_13-03-34-c88916.log'`
i can run it ml-100k
**To Reproduce**

Yaml file:
```
# dataset config : Context-aware Recommendation
load_col:
    inter: ['sso_id', 'article_id', 'label', 'timestamp']
    user: ['sso_id']
    item: ['article_id', 'section_primary']

LABEL_FIELD: label
eval_args:
    group_by: None
    mode: labeled
metrics: ['AUC', 'LogLoss']
valid_metric: AUC
```

runing with simple as 
`run_recbole(model='BPR', dataset='data/recbole', config_file_list=['experiments/test.yaml'])`

I have 3 files 
![image](https://github.com/RUCAIBox/RecBole/assets/38852155/c0c7903a-dcd3-4b44-8f63-b4aef7531519)

 - OS:  macOS 
- RecBole Version 1.1.1
 - Python Version 3.10
- PyTorch Version 2.0.1
