### ISSUE TITLE
[🐛BUG] train_neg_sample_args 负采样数量无效

### ISSUE THREAD

**Issue by han1254bjut** [RUCAIBox/RecBole#1801]
**Describe the bug**
我的yaml文件为
```yaml
train_neg_sample_args:          # (dict) Negative sampling configuration for model training.
      distribution: uniform         # (str) The distribution of negative items.
      sample_num: 20                # (int) The sampled num of negative items.
      alpha: 1.0                    # (float) The power of sampling probability for popularity distribution.
      dynamic: False                # (bool) Whether to use dynamic negative sampling.
      candidate_num: 0              # (int) The number of candidate negative items when dynamic negative sampling.
# Benchmark .inter file
benchmark_filename: ['train', 'valid', 'test']           # (list) List of pre-split user-item interaction suffix.
```
但是在debug的时候，计算calulate_loss时发现interaction中，只有与正样本一一对应的负样本，而我需要多个负样本，这里只给我一个负样本。
![1687767870141](https://github.com/RUCAIBox/RecBole/assets/113810665/5002e9fa-9a73-4a62-b5fb-2111f09e9159)
是因为我用了自己分割好的数据，还是因为我的模型设置了input_type = InputType.PAIRWISE？
