### ISSUE TITLE
[🐛BUG] DCN在mvlen100k下uni100与full的AUC差距过大

### ISSUE THREAD

**Issue by cywuuuu** [RUCAIBox/RecBole#2117]
**描述这个 bug**
对 bug 作一个清晰简明的描述。
DCN在mvlen100k下uni100与full的AUC差距过大, uni100时auc仅0.58左右，而full时auc为0.78左右，请问原因？谢谢
**如何复现**
复现这个 bug 的步骤：

1. 您引入的额外 yaml 文件
```
load_col:
    inter: ['user_id', 'item_id', 'rating', 'timestamp']
    user: ['user_id', 'age', 'gender', 'occupation']
    item: ['item_id', 'release_year', 'class']
threshold: {'rating': 4}
normalize_all: True
# model config
embedding_size: 10
# Training and evaluation config
epochs: 500
train_batch_size: 4096
eval_batch_size: 4096


topk: [1,2,3, 10, 100]
train_neg_sample_args: ~
metrics: ['AUC']
valid_metric: AUC
# eval_args:
#   # mode: uni100
device: 'cuda:0'
```
3. 您的代码
```
from recbole.quick_start import run_recbole

config_dict = {
    'device': 'cuda:0'  # 或 'cpu'，根据您的需求
}

run_recbole(model='DCN', dataset='ml-100k', config_file_list=['test.yaml'], config_dict=config_dict)

```
5. 您的运行脚本
直接运行即可
