### ISSUE TITLE
RuntimeError: Trying to create tensor with negative dimension -25: [-25]

### ISSUE THREAD

**Issue by zhuhh666** [RUCAIBox/RecBole#513]
**训练过程报错**
+ 为了测试，我收集了一份简单的日志，并按照要求把文件转换成recbole指定的格式，但是运行的时候报错:`RuntimeError: Trying to create tensor with negative dimension -25: [-25]`
+ 另外时间戳的单位是（s or ms？）

**以下是我的代码**
1. test.yaml
```yaml
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
load_col:
    inter: [rating, user_id, item_id, timestamp]

min_user_inter_num: 10
min_item_inter_num: 10
lowest_val:
    rating: 2
eval_setting: RO_RS,full
split_ratio: [0.8,0.1,0.1]
```
2. run.py
```
from recbole.config import Config
from recbole.data import create_dataset,data_preparation
from recbole.model.general_recommender import BPR
from recbole.trainer import Trainer
from logging import  getLogger
from recbole.utils import init_seed,init_logger

if __name__ == '__main__':
    # 初始化配置
    config = Config(model='BPR',dataset='test')
    config['data_path'] = './test_data/'
    config['dataset'] = 'test'
    # 初始随机种子，确保实验的可重复性
    init_seed(config['seed'],config['reproducibility'])
    ## 初始化日志
    init_logger(config)
    logger = getLogger()
    ## 将配置信息写入日志
    logger.info(config)
    ## 数据集创建和筛选
    dataset = create_dataset(config)
    logger.info(dataset)
    ## 数据集划分
    train_data,valid_data,test_data = data_preparation(config,dataset)

    ## 模型载入和初始化
    model = BPR(config,train_data).to(config['device'])
    logger.info(model)
    ## 训练器加载和初始化
    trainer = Trainer(config,model)

    # 模型训练
    best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)

    ## 模型评估
    test_result = trainer.evaluate(test_data)
    print(test_result)

```
**以下为完整的报错截图**
![](https://picgo06.oss-cn-zhangjiakou.aliyuncs.com/img/20201119192942.png)
**以下是我的数据集样式**
![](https://picgo06.oss-cn-zhangjiakou.aliyuncs.com/img/20201119193826.png)
**OS information:**
 - OS: windows
- RecBole Version 不太清楚
 - Python Version 3.6.12
- PyTorch Version 1.7.0
- cudatoolkit Version 11.1

新手上路，麻烦大大们了
