### ISSUE TITLE
[Question] How  does a session start and end?

### ISSUE THREAD

**Issue by mayaKaplansky** [RUCAIBox/RecBole#617]
Hi
I would like to try a few sequence models.
When I create the inter atomic file, can you tell me how can I mark a start and end of session?
None of the features can explicitly say so. 
Should each user id appear only once?
Thanks

**Comment by ShanleiMu** [comment]
- Q1
I think you can generate a field called `session_id` in your inter atomic file to indicate which session this interaction belongs to. And in each session, the sequence order is dependent on timestamp.
Then you can write something like these in your config file to load the data.
```YAML
USER_ID_FIELD: session_id
load_col:
  inter: [session_id, item_id, number of times, timestamp]
```

- Should each user id appear only once?
The same user id can appear in different sessions.
