### ISSUE TITLE
[🐛BUG] Caser `ValueError: Training loss is nan`

### ISSUE THREAD

**Issue by deklanw** [RUCAIBox/RecBole#679]
Keep getting this with Caser

```
ValueError: Training loss is nan
```

config

```yaml
dataset: ml-100k
model: Caser
eval_setting: TO_LS,full
```
