### ISSUE TITLE
[🐛BUG] Contextual model with temporal order tries to embed `timestamp`

### ISSUE THREAD

**Issue by deklanw** [RUCAIBox/RecBole#694]
```yaml
dataset: ml-100k
eval_setting: TO_LS,full
model: DCN
metrics: ["Recall", "MRR", "NDCG", "Hit", "MAP", "Precision"]
topk: [10, 20]
valid_metric: Precision@10
state: DEBUG
group_by_user: True
training_neg_sample_num: 1
threshold: null
load_col:
  inter: ["user_id", "item_id", "timestamp"]
  user: ["user_id", "age", "gender", "occupation"]
  item: ["item_id", "release_year", "class"]
```

truncated callstack

```
~/anaconda3/lib/python3.8/site-packages/recbole/model/abstract_recommender.py in embed_input_fields(self, interaction)
    372         print(interaction)
    373         for field_name in self.float_field_names:
--> 374             if len(interaction[field_name].shape) == 2:
    375                 float_fields.append(interaction[field_name])
    376             else:

~/anaconda3/lib/python3.8/site-packages/recbole/data/interaction.py in __getitem__(self, index)
    103     def __getitem__(self, index):
    104         if isinstance(index, str):
--> 105             return self.interaction[index]
    106         else:
    107             ret = {}

KeyError: 'timestamp'
```

I'm guessing this is because the `timestamp` is removed from the Interaction but at this part

https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/abstract_recommender.py#L370-L381

it's not excluding `timestamp` as a float field.
