### ISSUE TITLE
TopK for context dataloaders

### ISSUE THREAD

**Issue by stsl256** [RUCAIBox/RecBole#717]
Hi, are there any plans to implement recbole.utils.case_study.full_sort_topk function for context dataloaders? 

It works only for sequential and general dataloaders these days...

**Comment by chenyushuo** [comment]
Context models can use `recbole.utils.case_study.full_sort_topk`, because it is

**Comment by chenyushuo** [comment]
Context dataloaders can also use `recbole.utils.case_study.full_sort_topk`, because it is inherited from General dataloaders.
 
However, if you want to use full sort method for context-aware models, the `inter_feat` should only contain two fields: `user_id` and `item_id` (Because it is hard to construct the interaction feature for each item and user).
 
I guess your model was trained through CTR task, and the `inter_feat` of the model may have some other interaction features, so it didn’t work. If you want to use `recbole.utils.case_study.full_sort_topk` on your model, you'd better re-train the model through full sort task.
 
For more information about training models through full sort task, you can see [this page](https://recbole.io/docs/user_guide/evaluation_support.html). By the way, [unuse_col](https://recbole.io/docs/user_guide/data/data_args.html?highlight=unused_col#selectively-loading) in our config settings may be helpful.

**Comment by stsl256** [comment]
Still, I cant understand
This is a part of recbole.utils.case_study.full_sort_scores function, and it is obvious, that dataloader should be either GeneralFullDataLoader (not GeneralDataloader) of SequentialFullDataLoader. 
```
if isinstance(test_data, GeneralFullDataLoader):
        index = np.isin(test_data.user_df[uid_field].numpy(), uid_series)
        input_interaction = test_data.user_df[index]
        history_item = test_data.uid2history_item[input_interaction[uid_field]]
        history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)])
        history_col = torch.cat(list(history_item))
        history_index = history_row, history_col
elif isinstance(test_data, SequentialFullDataLoader):
        index = np.isin(test_data.uid_list, uid_series)
        input_interaction = test_data.augmentation(
            test_data.item_list_index[index], test_data.target_index[index], test_data.item_list_length[index]
        )
        history_index = None
else:
        raise NotImplementedError
```
I have ContextDataLoader which f.e doesn't have attribute 'uid_list'  (GeneralFullDataLoader has). I believe, that it is just not implemented (raise NotImplementedError). Am I right?

**Comment by chenyushuo** [comment]
It is true that `ContextDataLoader` doesn't have attribute 'uid_list'. But `ContextFullDataLoader` has this attribute. That is the reason why we recommender you to re-train the model through full sort task (not CTR task). Only in this way you can get ContextFullDataLoader to use `recbole.utils.case_study.full_sort_topk`.

**Comment by stsl256** [comment]
I am fairly new to recommender systems maybe and still do not understand you. 
Easily speaking, I have the following yaml config:
```
LABEL_FIELD: label
dataset: cpu_data
embedding_size: 64
epochs: 1
eval_batch_size: 64
eval_setting: TO_RS
gpu_id: 5
group_by_user: true
learning_rate: 0.001
load_col:
  inter:
  - user_id
  - item_id
  - rating
  - timestamp
  item:
  - item_id
  - cat_1
  user:
  - user_id
  - age
metrics:
- AUC
- LogLoss
model: WideDeep
show_progress: true
split_ratio:
- 0.75
- 0
- 0.25
state: INFO
stopping_step: 3
threshold:
  rating: 1
train_batch_size: 64
training_neg_sample_num: 0
unused_col:
  inter:
  - rating
  - timestamp
use_gpu: true
valid_metric: LogLoss
```

What should I do to make it work?
(notice, that I have unused_col)
I tried:
```
eval_setting: TO_RS,full
```
Throws:
```
ValueError: It can not validate with `full` when inter_feat have label_field [label].
```
I tried to fix it by deleting label and this led to some other mistakes. Can you help me?

**Comment by chenyushuo** [comment]
OK, I have changed your yaml config:
```yaml
LABEL_FIELD: label
dataset: cpu_data
embedding_size: 64
epochs: 1
eval_batch_size: 64
eval_setting: TO_RS,full
gpu_id: 5
group_by_user: true
learning_rate: 0.001
load_col:
  inter:
  - user_id
  - item_id
  - rating
  - timestamp
  item:
  - item_id
  - cat_1
  user:
  - user_id
  - age
metrics:
- Recall
- MRR
model: WideDeep
show_progress: true
split_ratio:
- 0.75
- 0
- 0.25
state: INFO
stopping_step: 3
threshold: ~
train_batch_size: 64
training_neg_sample_num: 1
unused_col:
  inter:
  - rating
  - timestamp
use_gpu: true
valid_metric: MRR@10
```

I mainly changed these configuration:
```yaml
eval_setting: TO_RS,full
metrics:
- Recall
- MRR
threshold: ~
training_neg_sample_num: 1
valid_metric: MRR@10
```

Besides, we have fixed a runtime error when `ContextFullDataLoader` is empty in #723 . You can modify your local code to avoid runtime error.
