### ISSUE TITLE
数据集原子文件的处理和格式 没有文档

### ISSUE THREAD

**Issue by zyjcs** [RUCAIBox/RecBole#810]
**您希望添加的功能是否与某个问题相关？**
https://recbole.io/cn/atomic_files.html  这个网址打不开，请问哪里有关于自定义数据集处理的文档呢，怎么处理自己的数据集呢？

**描述您希望的解决方案**
非常感谢这个项目的人员
**描述您考虑的替代方案**
关于您考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
您可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by hyp1231** [comment]
您好，在大陆或许需要科学上网以访问 https://recbole.io/cn/atomic_files.html ，或者您可以先暂时参考 https://github.com/RUCAIBox/RecSysDatasets 中的原子文件样例及一些 benchmark 的数据处理脚本。

对于官网的网络访问问题，我们也会尽快解决。

**Comment by zyjcs** [comment]
https://github.com/RUCAIBox/RecSysDatasets/issues/91


感谢回复您好 请看这个issue，想问下 自定义的数据集应该怎么处理呢，这个issue是什么原因呢

**Comment by zyjcs** [comment]
**(base) @B-RGRXML7H-0008 RecBole % python run_recbole.py --model=DeepFM --dataset=book-crossing --config-files=test.yaml**
15 Apr 17:39    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = dataset/book-crossing
show_progress = True

Training Hyper Parameters:
checkpoint_dir = saved
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
training_neg_sample_num = 0
training_neg_sample_distribution = uniform
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
draw_loss_pic = False
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_setting = RO_RS
group_by_user = False
split_ratio = [0.8, 0.1, 0.1]
leave_one_num = 2
real_time_process = False
metrics = ['AUC', 'LogLoss']
topk = [10]
valid_metric = AUC
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id']}
unload_col = None
unused_col = None
additional_feat_suffix = None
lowest_val = None
highest_val = None
equal_val = None
not_equal_val = None
max_user_inter_num = None
min_user_inter_num = 0
max_item_inter_num = None
min_item_inter_num = 0
fields_in_same_space = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id

Other Hyper Parameters:
embedding_size = 10
mlp_hidden_size = [128, 128, 128]
dropout_prob = 0.2
rm_dup_inter = None
filter_inter_by_user_or_item = True
SOURCE_ID_FIELD = source_id
TARGET_ID_FIELD = target_id
benchmark_filename = None
MODEL_TYPE = ModelType.CONTEXT
config-files = test.yaml
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.INDIVIDUAL
valid_metric_bigger = True
device = cpu
train_neg_sample_args = {'strategy': 'none'}


15 Apr 17:39    INFO  book-crossing
The number of users: 105284
Average actions of users: 10.920851419507423
The number of items: 340557
Average actions of items: 3.376184827164989
The number of inters: 1149780
The sparsity of the dataset: 99.996793268765%
Remain Fields: ['user_id', 'item_id']
15 Apr 17:39    INFO  Build [ContextDataLoader] for [train] with format [InputType.POINTWISE]
15 Apr 17:39    INFO  [train] No Negative Sampling
15 Apr 17:39    INFO  [train] batch_size = [2048], shuffle = [True]

15 Apr 17:39    INFO  Build [ContextDataLoader] for [evaluation] with format [InputType.POINTWISE]
15 Apr 17:39    INFO  Evaluation Setting:
	No Grouping
	Ordering: {'strategy': 'shuffle'}
	Splitting: {'strategy': 'by_ratio', 'ratios': [0.8, 0.1, 0.1]}
	No Negative Sampling
15 Apr 17:39    INFO  [evaluation] batch_size = [4096], shuffle = [False]

15 Apr 17:39    INFO  DeepFM(
  (token_embedding_table): FMEmbedding(
    (embedding): Embedding(445841, 10)
  )
  (first_order_linear): FMFirstOrderLinear(
    (token_embedding_table): FMEmbedding(
      (embedding): Embedding(445841, 1)
    )
  )
  (fm): BaseFactorizationMachine()
  (mlp_layers): MLPLayers(
    (mlp_layers): Sequential(
      (0): Dropout(p=0.2, inplace=False)
      (1): Linear(in_features=20, out_features=128, bias=True)
      (2): ReLU()
      (3): Dropout(p=0.2, inplace=False)
      (4): Linear(in_features=128, out_features=128, bias=True)
      (5): ReLU()
      (6): Dropout(p=0.2, inplace=False)
      (7): Linear(in_features=128, out_features=128, bias=True)
      (8): ReLU()
    )
  )
  (deep_predict_layer): Linear(in_features=128, out_features=1, bias=True)
  (sigmoid): Sigmoid()
  (loss): BCELoss()
)
Trainable parameters: 4940093
Train     0:   0%|                                                                                                         | 0/450 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/Users/zengyujian/RecBole/recbole/quick_start/quick_start.py", line 54, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "/Users/zengyujian/RecBole/recbole/trainer/trainer.py", line 270, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "/Users/zengyujian/RecBole/recbole/trainer/trainer.py", line 159, in _train_epoch
    losses = loss_func(interaction)
  File "/Users/zengyujian/RecBole/recbole/model/context_aware_recommender/deepfm.py", line 68, in calculate_loss
    label = interaction[self.LABEL]
  File "/Users/zengyujian/RecBole/recbole/data/interaction.py", line 105, in __getitem__
    return self.interaction[index]
KeyError: 'label'
(base) @B-RGRXML7H-0008 RecBole % python run_recbole.py --model=DeepFM --dataset=book-crossing --config-files=test.yaml



test.yaml 如下
#threshold: {'rating': 4}
load_col: 
    inter: ['user_id', 'item_id', 'rating']
    user: ['user_id', 'location', 'age']
    item: ['item_id', 'book_title', 'book_author','publication_year','publisher']
请问这个错是什么意思呢，没有标签列吗   使用的book-crossing 数据集 
![image](https://user-images.githubusercontent.com/18757695/114849069-f95a2800-9e11-11eb-947d-2d93fd111c36.png)
请问是还需要在哪里设置吗

**Comment by zyjcs** [comment]
![image](https://user-images.githubusercontent.com/18757695/114851701-b2b9fd00-9e14-11eb-8b28-1718e3efa29e.png)
请问是每个模型和每个数据集都要单独设置一个yaml文件吗  ，我运行book-crossing数据集是不是要新建一个book-crossing.yaml？

**Comment by 2017pxy** [comment]
@zyjcs 你好，关于你上面的那个报错:
>请问这个错是什么意思呢，没有标签列吗 使用的book-crossing 数据集

应该是因为没有设置label列，你在`.yaml`文件里面把`threshold`那一行注释了，所以整个数据集是没有label的，无法计算AUC类指标。建议你把`threshold`那一行恢复后再试试。

关于yaml文件：
>请问是每个模型和每个数据集都要单独设置一个yaml文件吗 ，我运行book-crossing数据集是不是要新建一个book-crossing.yaml？

对于每一个数据集，可能需要针对数据集更改一些设置，所以可能需要修改yaml文件，但和yaml文件名无关，你完全可以继续使用`test.yaml`文件，并在该文件中进行修改，当然，为了方便区分，你也可以创建一个新的yaml文件。只要你在每次运行的时候，在命令行设置好你要输入的yaml文件名就行

**Comment by zyjcs** [comment]
![image](https://user-images.githubusercontent.com/18757695/114856149-56a5a780-9e19-11eb-8fa9-b9e55d186b7e.png)
![image](https://user-images.githubusercontent.com/18757695/114856193-67eeb400-9e19-11eb-94dd-b10ece96334c.png)
你好 还是不行呢 这个threhold表示什么意思？

**Comment by zyjcs** [comment]
python run_recbole.py --model=DeepFM --dataset=book-crossing --config-files=test.yaml

**Comment by zyjcs** [comment]
> python run_recbole.py --model=DeepFM --dataset=book-crossing --config-files=test.yaml

这是运行的命令

**Comment by zyjcs** [comment]
大佬 可以加个qq请教下吗 1136899882

**Comment by 2017pxy** [comment]
@zyjcs 你好，因为你没有提供你的完整yaml文件，我只能通过你的config输出大致估计你的配置需求。
我按照以下的yaml成功在book-crossing 数据集上运行了DeepFM，你可以进行参考：
```
# dataset config
field_separator: "\t"  #指定数据集field的分隔符
seq_separator: " "   #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: item_id #指定物品id域
RATING_FIELD: rating   #指定打分rating域
NEG_PREFIX: neg_   #指定负采样前缀

#指定从什么文件里读什么列，这里就是从ml-1m.inter里面读取user_id, item_id, rating, timestamp这四列
threshold: {'rating': 4}
load_col:
  inter: ['user_id', 'item_id', 'rating']
  user: ['user_id', 'location', 'age']
  item: ['item_id', 'book_title', 'book_author','publication_year','publisher']

# training settings
epochs: 500  #训练的最大轮数
train_batch_size: 2048 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
training_neg_sample_num: 0 #负采样数目
eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了

# evalution settings
eval_setting: RO_RS #对数据随机重排，设置按比例划分数据集，且使用全排序
group_by_user: True #是否将一个user的记录划到一个组里，当eval_setting使用RO_RS的时候该项必须是True
split_ratio: [0.8,0.1,0.1] #切分比例
metrics: ['AUC'] #评测标准
topk: None #评测标准使用topk，设置成10评测标准就是["Recall@10", "MRR@10", "NDCG@10", "Hit@10", "Precision@10"]
valid_metric: AUC #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size
```
运行指令如下：
```
python run_recbole.py --model=DeepFM --dataset=book-crossing --config_files=test.yaml
```

此外，关于各个参数的具体含义（例如什么是threshold？），请参考我们的[官方文档](https://recbole.io/docs/user_guide/config_settings.html)，文档中对所有参数都有详细的描述。在你遇到问题时，请先仔细阅读文档，然后再向我们提问。
最后，欢迎通过提issue或者discussion的方式向我们提问，我们会尽快回复。
