### ISSUE TITLE
Top K recommendations using context aware recommendation models

### ISSUE THREAD

**Issue by khajaphysist** [RUCAIBox/RecBole#819]
Thanks for help with https://github.com/RUCAIBox/RecBole/issues/817, and this is its continuation as I am having hard time figuring out what I am doing wrong.

As suggested in https://github.com/RUCAIBox/RecBole/issues/817, I am trying to use Context-aware model [FM](https://recbole.io/docs/user_guide/model/context/fm.html) to get top k recommended items (`jobs` that user would `apply`) for each user with following yaml config

```yaml
load_col:
    inter: [user_id, item_id, view, apply, timestamp]
    item: [item_id, feat1, feat2, feat3, ...]
    user: [user_id, feat1, feat2, feat3, ...]
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
LABEL_FIELD: apply

eval_setting: TO_LS,full
group_by_user: True
threshold: ~

metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 100
valid_metric: MRR@100
```

where `data.inter` is like following

```tsv
user_id:token	item_id:token	timestamp:float	apply:float	view:float
1	1	1583020800	0	1
2	1	1583020900	0	1
3	2	1583021000	0	1
2	2	1583022000	1	0
```

But I get following error

```
ValueError: It can not validate with `full` when inter_feat have label_field [apply].
```

After searching a while I followed the suggestion in https://github.com/RUCAIBox/RecBole/issues/676#issuecomment-760626385 and changed my config to following

```yaml
load_col:
    inter: [user_id, item_id]
    item: [item_id, feat1, feat2, feat3, ...]
    user: [user_id, feat1, feat2, feat3, ...]
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id

eval_setting: RO_RS,full
training_neg_sample_num: 1
group_by_user: True
threshold: ~

metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 100
valid_metric: MRR@100
eval_step: 10
```

after which it runs fine, but train loss does not change at all. Below is the full config printed when running

```bash
Fri 30 Apr 2021 16:18:38 INFO General Hyper Parameters: 
gpu_id=0
use_gpu=True
seed=2020
state=INFO
reproducibility=True
data_path=dataset/test
show_progress=True

Training Hyper Parameters: 
checkpoint_dir=saved
epochs=300
train_batch_size=2048
learner=adam
learning_rate=0.001
training_neg_sample_num=1
training_neg_sample_distribution=uniform
eval_step=10
stopping_step=10

Evaluation Hyper Parameters: 
eval_setting=RO_RS,full
group_by_user=True
split_ratio=[0.8, 0.1, 0.1]
leave_one_num=2
real_time_process=False
metrics=['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk=10
valid_metric=MRR@10
eval_batch_size=4096

Dataset Hyper Parameters: 
field_separator=	
seq_separator= 
USER_ID_FIELD=user_id
ITEM_ID_FIELD=item_id
RATING_FIELD=rating
TIME_FIELD=timestamp
seq_len=None
LABEL_FIELD=label
threshold=None
NEG_PREFIX=neg_
load_col={'inter': ['user_id', 'item_id'], 'item': ['item_id', 'feat1', 'feat2'], 'user': ['user_id', 'feat1', 'feat2', 'feat3']}
unload_col=None
unused_col=None
additional_feat_suffix=None
lowest_val=None
highest_val=None
equal_val=None
not_equal_val=None
max_user_inter_num=None
min_user_inter_num=0
max_item_inter_num=None
min_item_inter_num=0
fields_in_same_space=None
preload_weight=None
normalize_field=None
normalize_all=None
ITEM_LIST_LENGTH_FIELD=item_length
LIST_SUFFIX=_list
MAX_ITEM_LIST_LENGTH=50
POSITION_FIELD=position_id
HEAD_ENTITY_ID_FIELD=head_id
TAIL_ENTITY_ID_FIELD=tail_id
RELATION_ID_FIELD=relation_id
ENTITY_ID_FIELD=entity_id


Fri 30 Apr 2021 16:18:40 INFO test
The number of users: 67145
Average actions of users: 11.957002859525796
The number of items: 124058
Average actions of items: 6.471549368435477
The number of inters: 802841
The sparsity of the dataset: 99.99036190750924%
Remain Fields: ['user_id', 'item_id', 'feat1', 'feat2', 'feat3', 'feat1', 'feat2']
Fri 30 Apr 2021 16:18:42 INFO Build [ModelType.CONTEXT] DataLoader for [train] with format [InputType.POINTWISE]
Fri 30 Apr 2021 16:18:42 INFO Evaluation Setting:
	Group by user_id
	Ordering: {'strategy': 'shuffle'}
	Splitting: {'strategy': 'by_ratio', 'ratios': [0.8, 0.1, 0.1]}
	Negative Sampling: {'strategy': 'by', 'distribution': 'uniform', 'by': 1}
Fri 30 Apr 2021 16:18:42 INFO batch_size = [[2048]], shuffle = [True]

Fri 30 Apr 2021 16:18:42 INFO Build [ModelType.CONTEXT] DataLoader for [evaluation] with format [InputType.POINTWISE]
Fri 30 Apr 2021 16:18:42 INFO Evaluation Setting:
	Group by user_id
	Ordering: {'strategy': 'shuffle'}
	Splitting: {'strategy': 'by_ratio', 'ratios': [0.8, 0.1, 0.1]}
	Negative Sampling: {'strategy': 'full', 'distribution': 'uniform'}
Fri 30 Apr 2021 16:18:42 INFO batch_size = [[4096, 4096]], shuffle = [False]

Fri 30 Apr 2021 16:18:42 WARNING Batch size is changed to 124058.
Fri 30 Apr 2021 16:18:42 WARNING Batch size is changed to 124058.
Fri 30 Apr 2021 16:18:44 INFO FM(
  (token_embedding_table): FMEmbedding(
    (embedding): Embedding(191980, 10)
  )
  (float_embedding_table): Embedding(1, 10)
  (first_order_linear): FMFirstOrderLinear(
    (token_embedding_table): FMEmbedding(
      (embedding): Embedding(191980, 1)
    )
    (float_embedding_table): Embedding(1, 1)
  )
  (fm): BaseFactorizationMachine()
  (sigmoid): Sigmoid()
  (loss): BCELoss()
)
Trainable parameters: 2111792
Fri 30 Apr 2021 16:18:46 INFO epoch 0 training [time: 2.15s, train loss:33750.0000]
Fri 30 Apr 2021 16:18:48 INFO epoch 1 training [time: 2.15s, train loss:33750.0000]
Fri 30 Apr 2021 16:18:50 INFO epoch 2 training [time: 2.13s, train loss:33750.0000]
Fri 30 Apr 2021 16:18:52 INFO epoch 3 training [time: 2.13s, train loss:33750.0000]
```

As you can see the model does not learn at all and train loss stays same. Can you please point me in the right direction? This is what I am trying to achieve

- There are multiple user-item behavior types (view, apply) which I have hot encoded in `data.inter`
- Data has user features, item features, interaction features and timestamp
- I want to generate top k items that would optimize `apply` user behavior

Thanks.

**Comment by hyp1231** [comment]
Hi @khajaphysist,

Could you please provide a sample data (a few hundred lines of `.inter`, `.item` and `.user` files after desensitization), we will test on it, thanks.

If it's not convenient to share publicly, you can send me an email, [houyupeng@ruc.edu.cn](mailto:houyupeng@ruc.edu.cn).

**Comment by khajaphysist** [comment]
Hi @hyp1231,

Thanks for the help here are sample files [anon.zip](https://github.com/RUCAIBox/RecBole/files/6438447/anon.zip), it has sample.user, sample.item, sample.inter files with `field_separator: ,` and `seq_separator: |`.

**Comment by khajaphysist** [comment]
@hyp1231 
After going through the code a lot, I figured that https://github.com/RUCAIBox/RecBole/issues/676#issuecomment-760626385 solved my problem of running above dataset with ranking metrics. I used following config

```yaml
field_separator: ','
seq_separator: '|'
load_col:
    inter: [user_id, item_id]
    item: [item_id,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,feat11]
    user: [user_id,ufeat1,ufeat2,ufeat3,ufeat4,ufeat5,ufeat6]
eval_step: 5
learner: adagrad
eval_setting: RO_RS,pop100
group_by_user: False
training_neg_sample_num: 1
metrics: ["Recall","MRR","NDCG","Hit","Precision"]
valid_metric: MRR@10
threshold: ~
```

It took a lot of time to figure out as I ran into this bug https://github.com/RUCAIBox/RecBole/issues/826

Thanks.
