### ISSUE TITLE
rating_field和label_field的定义

### ISSUE THREAD

**Issue by miloooooz** [RUCAIBox/RecBole#975]
您好，我想确认一下rating和label在RecBole中的定义是什么？
从这个问题我了解到如果想要分析某个值，比如在这里是我的商品评分，那就将它列为label #817  ，可是这样的话rating_field的含义是什么呢？并且这位提问者最终在 #819  训练context-aware的时候`.inter`文件并没有定义任何除了user_id和item_id以外的feature，config如下：
```
field_separator: ','
seq_separator: '|'
load_col:
    inter: [user_id, item_id]
    item: [item_id,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,feat11]
    user: [user_id,ufeat1,ufeat2,ufeat3,ufeat4,ufeat5,ufeat6]
eval_step: 5
learner: adagrad
eval_setting: RO_RS,pop100
group_by_user: False
training_neg_sample_num: 1
metrics: ["Recall","MRR","NDCG","Hit","Precision"]
valid_metric: MRR@10
threshold: ~
```
这种情况下模型是根据什么来给user和item的pair打分的呢？这里困扰了我很久。
我们需要预测的标准是rating吗？这个label的设置是作为feature来告诉模型正负样本的定义还是作为模型的预测根据，最终输出一个概率来表示预测为1的可能性？
非常感谢。
