### ISSUE TITLE
How to convert external data suitable for recbole models

### ISSUE THREAD

**Issue by satsaras** [RUCAIBox/RecBole#983]
For now I have seen that recbole experimentations are working with recbole provided datasets processed in specific format. How can we convert our own data suitable in format suitable for recbole? In your documentation its not quite clear

**Comment by chenyuwuxin** [comment]
@satsaras Hello, thanks for your attention to RecBole!
RecBole has 28 build-in datasets for users to quickly get start. (detailed as [Dataset List](https://recbole.io/dataset_list.html).)
If you want to use your own dataset, you need to do the following steps:

- Prepare atomic files
RecBole designs an input data format called **Atomic Files** and you need to convert your raw data into **Atomic Files** format before data loading at first.
For example,the converted atomic files of ml-1m are like:
**ml-1m.inter**

  |  user_id:token | item_id:token | rating:float | timestamp:float |
  |  ----  | ----  | ----  | ---- |
  | 1 | 1193 | 5 | 978300760 |
  | 1 | 661 | 3 | 978302109 |

   **ml-1m.user**

  |  user_id:token | age:token | gender:token | occupation:token | zip_code:token |
  |  ----  | ----  | ----  | ---- | ---- |
  | 1 | 1 | 5 | F | 10 | 48067 |
  | 2 | 56 | M | 16 | 70072 |

   **ml-1m.item**

  |  user_id:token | movie_title:token_seq | release_year:token | genre:token_seq |
  |  ----  | ----  | ----  | ---- |
  | 1 | Toy Story | 1995 | Animation Children’s Comedy |
  | 1 | Jumanji | 1995 | Adventure Children’s Fantasy |

  For other datasets, please refer to [Atomic Files](https://recbole.io/docs/user_guide/data/atomic_files.html) for specific format.

- Set data path
You need to set the data path in config when you want to use new dataset. The name of atomic files, name of dir that containing atomic files and `config['dataset']` should be the same, and the `data_path` in your config should be the parent dir of the directory that contains atomic files.
**Folder view**:
  ```
  ~/xxx/yyy/ml-1m/
  ├── ml-1m.inter
  ├── ml-1m.item
  ├── ml-1m.kg
  ├── ml-1m.link
  └── ml-1m.user
  ```

  **Config view**:
  ```
  data_path: ~/xxx/yyy/
  dataset: ml-1m
  ```
- Set dataset processing configuration
  Finally you should set the dataset processing information in the configuration file. For example, we conduct 10-core filtering, removing the ratings which are smaller than 3, the time of the record should be earlier than 97830000, and we only load inter data. And we want to leverage random ordering, ratio-based splitting and full ranking with all item candidates, the splitting ratio is set as 8:1:1.The `yaml` file should be like:
  ```
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  
  load_col:
      inter: [user_id, item_id, rating, timestamp]
  
  user_inter_num_interval: "[10,inf)"
  item_inter_num_interval: "[10,inf)"
  val_interval:
      rating: "[3,inf)"
      timestamp: "[97830000, inf)"
  eval_args:
      split: {'RS': [8,1,1]}
      group_by: user
      order: RO
      mode: full
  ```

You can refer to [newdataset](https://recbole.io/docs/user_guide/usage/running_new_dataset.html) for more details and thank you again for your attention to RecBole.
